name: Build & Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24.0'

    - name: Build executable
      run: |
        mkdir -p bin
        go build -o bin/myapp ./main
 
   - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-binary
        path: bin/myapp

    - name: Run tests
      run: go test ./...

